### ISSUE TITLE
One button to clear survey and contest result

### ISSUE THREAD

**Issue by injan0913** [catsass19/Sapporo#25]
Might be easy to clear related document in MongoDB.

**Comment by catsass19** [comment]
I'll add it on Saturday

**Comment by injan0913** [comment]
Good good. Maybe I can help on doing tests.

**Comment by catsass19** [comment]
Ha that will be good! And we might need Kenny for the automation testing. If you need me in the office just let me know, I can go in the morning.

**Comment by catsass19** [comment]
Added support to clear survey and userData. The button is under system config page. When the button is pressed, all current user will be logged out. Once they login back, a clean userData for them will be created.

**Comment by injan0913** [comment]
a35515d
